set_mediaroom_source:
  fields:
    media_room_id:
      example: 102
      selector:
        number:
          min: 0
          max: 100000
          step: 1
          mode: box
    source_id:
      example: 203
      selector:
        number:
          min: 0
          max: 100000
          step: 1
          mode: box